package com.guntzergames.medievalwipeout.enums;

public enum Phase {

	BEFORE_RESOURCE_CHOOSE, DURING_RESOURCE_CHOOSE, AFTER_RESOURCE_CHOOSE,
	BEFORE_RESOURCE_SELECT, DURING_RESOURCE_SELECT, AFTER_RESOURCE_SELECT,
	BEFORE_DECK_DRAW, DURING_DECK_DRAW, AFTER_DECK_DRAW,
	BEFORE_PLAY, DURING_PLAY, AFTER_PLAY;

}